# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.trips_trips import TripsTrips  # noqa: F401,E501
from swagger_server import util


class Trips(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, version: str=None, trips: TripsTrips=None):  # noqa: E501
        """Trips - a model defined in Swagger

        :param version: The version of this Trips.  # noqa: E501
        :type version: str
        :param trips: The trips of this Trips.  # noqa: E501
        :type trips: TripsTrips
        """
        self.swagger_types = {
            'version': str,
            'trips': TripsTrips
        }

        self.attribute_map = {
            'version': 'version',
            'trips': 'trips'
        }
        self._version = version
        self._trips = trips

    @classmethod
    def from_dict(cls, dikt) -> 'Trips':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The trips of this Trips.  # noqa: E501
        :rtype: Trips
        """
        return util.deserialize_model(dikt, cls)

    @property
    def version(self) -> str:
        """Gets the version of this Trips.


        :return: The version of this Trips.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version: str):
        """Sets the version of this Trips.


        :param version: The version of this Trips.
        :type version: str
        """

        self._version = version

    @property
    def trips(self) -> TripsTrips:
        """Gets the trips of this Trips.


        :return: The trips of this Trips.
        :rtype: TripsTrips
        """
        return self._trips

    @trips.setter
    def trips(self, trips: TripsTrips):
        """Sets the trips of this Trips.


        :param trips: The trips of this Trips.
        :type trips: TripsTrips
        """

        self._trips = trips
