# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.trip import Trip  # noqa: F401,E501
from swagger_server import util


class TripsTrips(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, version: str='2.0.0', trips: List[Trip]=None):  # noqa: E501
        """TripsTrips - a model defined in Swagger

        :param version: The version of this TripsTrips.  # noqa: E501
        :type version: str
        :param trips: The trips of this TripsTrips.  # noqa: E501
        :type trips: List[Trip]
        """
        self.swagger_types = {
            'version': str,
            'trips': List[Trip]
        }

        self.attribute_map = {
            'version': 'version',
            'trips': 'trips'
        }
        self._version = version
        self._trips = trips

    @classmethod
    def from_dict(cls, dikt) -> 'TripsTrips':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The trips_trips of this TripsTrips.  # noqa: E501
        :rtype: TripsTrips
        """
        return util.deserialize_model(dikt, cls)

    @property
    def version(self) -> str:
        """Gets the version of this TripsTrips.


        :return: The version of this TripsTrips.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version: str):
        """Sets the version of this TripsTrips.


        :param version: The version of this TripsTrips.
        :type version: str
        """

        self._version = version

    @property
    def trips(self) -> List[Trip]:
        """Gets the trips of this TripsTrips.


        :return: The trips of this TripsTrips.
        :rtype: List[Trip]
        """
        return self._trips

    @trips.setter
    def trips(self, trips: List[Trip]):
        """Sets the trips of this TripsTrips.


        :param trips: The trips of this TripsTrips.
        :type trips: List[Trip]
        """

        self._trips = trips
