# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.feature import Feature  # noqa: F401,E501
from swagger_server import util


class FeatureCollection(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, type: str=None, features: List[Feature]=None):  # noqa: E501
        """FeatureCollection - a model defined in Swagger

        :param type: The type of this FeatureCollection.  # noqa: E501
        :type type: str
        :param features: The features of this FeatureCollection.  # noqa: E501
        :type features: List[Feature]
        """
        self.swagger_types = {
            'type': str,
            'features': List[Feature]
        }

        self.attribute_map = {
            'type': 'type',
            'features': 'features'
        }
        self._type = type
        self._features = features

    @classmethod
    def from_dict(cls, dikt) -> 'FeatureCollection':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The featureCollection of this FeatureCollection.  # noqa: E501
        :rtype: FeatureCollection
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this FeatureCollection.


        :return: The type of this FeatureCollection.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this FeatureCollection.


        :param type: The type of this FeatureCollection.
        :type type: str
        """
        allowed_values = ["FeatureCollection"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def features(self) -> List[Feature]:
        """Gets the features of this FeatureCollection.


        :return: The features of this FeatureCollection.
        :rtype: List[Feature]
        """
        return self._features

    @features.setter
    def features(self, features: List[Feature]):
        """Sets the features of this FeatureCollection.


        :param features: The features of this FeatureCollection.
        :type features: List[Feature]
        """
        if features is None:
            raise ValueError("Invalid value for `features`, must not be `None`")  # noqa: E501

        self._features = features
