# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Links(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, first: str=None, last: str=None, prev: str=None, next: str=None):  # noqa: E501
        """Links - a model defined in Swagger

        :param first: The first of this Links.  # noqa: E501
        :type first: str
        :param last: The last of this Links.  # noqa: E501
        :type last: str
        :param prev: The prev of this Links.  # noqa: E501
        :type prev: str
        :param next: The next of this Links.  # noqa: E501
        :type next: str
        """
        self.swagger_types = {
            'first': str,
            'last': str,
            'prev': str,
            'next': str
        }

        self.attribute_map = {
            'first': 'first',
            'last': 'last',
            'prev': 'prev',
            'next': 'next'
        }
        self._first = first
        self._last = last
        self._prev = prev
        self._next = next

    @classmethod
    def from_dict(cls, dikt) -> 'Links':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The links of this Links.  # noqa: E501
        :rtype: Links
        """
        return util.deserialize_model(dikt, cls)

    @property
    def first(self) -> str:
        """Gets the first of this Links.


        :return: The first of this Links.
        :rtype: str
        """
        return self._first

    @first.setter
    def first(self, first: str):
        """Sets the first of this Links.


        :param first: The first of this Links.
        :type first: str
        """

        self._first = first

    @property
    def last(self) -> str:
        """Gets the last of this Links.


        :return: The last of this Links.
        :rtype: str
        """
        return self._last

    @last.setter
    def last(self, last: str):
        """Sets the last of this Links.


        :param last: The last of this Links.
        :type last: str
        """

        self._last = last

    @property
    def prev(self) -> str:
        """Gets the prev of this Links.


        :return: The prev of this Links.
        :rtype: str
        """
        return self._prev

    @prev.setter
    def prev(self, prev: str):
        """Sets the prev of this Links.


        :param prev: The prev of this Links.
        :type prev: str
        """

        self._prev = prev

    @property
    def next(self) -> str:
        """Gets the next of this Links.


        :return: The next of this Links.
        :rtype: str
        """
        return self._next

    @next.setter
    def next(self, next: str):
        """Sets the next of this Links.


        :param next: The next of this Links.
        :type next: str
        """

        self._next = next
