# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.geometry import Geometry  # noqa: F401,E501
from swagger_server.models.point3_d import Point3D  # noqa: F401,E501
from swagger_server import util


class MultiLineString(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, type: str=None, coordinates: List[List[Point3D]]=None):  # noqa: E501
        """MultiLineString - a model defined in Swagger

        :param type: The type of this MultiLineString.  # noqa: E501
        :type type: str
        :param coordinates: The coordinates of this MultiLineString.  # noqa: E501
        :type coordinates: List[List[Point3D]]
        """
        self.swagger_types = {
            'type': str,
            'coordinates': List[List[Point3D]]
        }

        self.attribute_map = {
            'type': 'type',
            'coordinates': 'coordinates'
        }
        self._type = type
        self._coordinates = coordinates

    @classmethod
    def from_dict(cls, dikt) -> 'MultiLineString':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The multiLineString of this MultiLineString.  # noqa: E501
        :rtype: MultiLineString
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this MultiLineString.

        the geometry type  # noqa: E501

        :return: The type of this MultiLineString.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this MultiLineString.

        the geometry type  # noqa: E501

        :param type: The type of this MultiLineString.
        :type type: str
        """
        allowed_values = ["point", "lineString", "polygon", "multiPoint", "multiLineString", "multiPolygon"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def coordinates(self) -> List[List[Point3D]]:
        """Gets the coordinates of this MultiLineString.


        :return: The coordinates of this MultiLineString.
        :rtype: List[List[Point3D]]
        """
        return self._coordinates

    @coordinates.setter
    def coordinates(self, coordinates: List[List[Point3D]]):
        """Sets the coordinates of this MultiLineString.


        :param coordinates: The coordinates of this MultiLineString.
        :type coordinates: List[List[Point3D]]
        """

        self._coordinates = coordinates
