# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.links import Links  # noqa: F401,E501
from swagger_server.models.status import Status  # noqa: F401,E501
from swagger_server import util


class Statusses(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, version: str=None, vehicles_status: List[Status]=None, links: Links=None):  # noqa: E501
        """Statusses - a model defined in Swagger

        :param version: The version of this Statusses.  # noqa: E501
        :type version: str
        :param vehicles_status: The vehicles_status of this Statusses.  # noqa: E501
        :type vehicles_status: List[Status]
        :param links: The links of this Statusses.  # noqa: E501
        :type links: Links
        """
        self.swagger_types = {
            'version': str,
            'vehicles_status': List[Status],
            'links': Links
        }

        self.attribute_map = {
            'version': 'version',
            'vehicles_status': 'vehicles_status',
            'links': 'links'
        }
        self._version = version
        self._vehicles_status = vehicles_status
        self._links = links

    @classmethod
    def from_dict(cls, dikt) -> 'Statusses':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The statusses of this Statusses.  # noqa: E501
        :rtype: Statusses
        """
        return util.deserialize_model(dikt, cls)

    @property
    def version(self) -> str:
        """Gets the version of this Statusses.


        :return: The version of this Statusses.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version: str):
        """Sets the version of this Statusses.


        :param version: The version of this Statusses.
        :type version: str
        """
        if version is None:
            raise ValueError("Invalid value for `version`, must not be `None`")  # noqa: E501

        self._version = version

    @property
    def vehicles_status(self) -> List[Status]:
        """Gets the vehicles_status of this Statusses.


        :return: The vehicles_status of this Statusses.
        :rtype: List[Status]
        """
        return self._vehicles_status

    @vehicles_status.setter
    def vehicles_status(self, vehicles_status: List[Status]):
        """Sets the vehicles_status of this Statusses.


        :param vehicles_status: The vehicles_status of this Statusses.
        :type vehicles_status: List[Status]
        """
        if vehicles_status is None:
            raise ValueError("Invalid value for `vehicles_status`, must not be `None`")  # noqa: E501

        self._vehicles_status = vehicles_status

    @property
    def links(self) -> Links:
        """Gets the links of this Statusses.


        :return: The links of this Statusses.
        :rtype: Links
        """
        return self._links

    @links.setter
    def links(self, links: Links):
        """Sets the links of this Statusses.


        :param links: The links of this Statusses.
        :type links: Links
        """
        if links is None:
            raise ValueError("Invalid value for `links`, must not be `None`")  # noqa: E501

        self._links = links
