# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class VehicleType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    BICYCLE = "bicycle"
    BUS = "bus"
    CARGO_BICYCLE = "cargo_bicycle"
    CAR = "car"
    DELIVERY_ROBOT = "delivery_robot"
    MOPED = "moped"
    MOTORCYCLE = "motorcycle"
    SCOOTER_STANDING = "scooter_standing"
    SCOOTER_SEATED = "scooter_seated"
    TRUCK = "truck"
    OTHER = "other"
    def __init__(self):  # noqa: E501
        """VehicleType - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'VehicleType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The vehicle_type of this VehicleType.  # noqa: E501
        :rtype: VehicleType
        """
        return util.deserialize_model(dikt, cls)
